default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: challenge_development
  password: sendgridchallenge!
test:
  <<: *default
  database: challenge_test

production:
  <<: *default
  database: challenge_production
  username: challenge
  password: <%= ENV['BLANK_DATABASE_PASSWORD'] %>
